env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: python
python: 3.8
node_js: lts/*
jdk: openjdk8
addons:
  apt:
    update: false
    packages:
      - curl
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash
    stop_any 3000 5000 8000 8080 80
  - |
    export PATH=$HOME/.local/bin:$PATH
    python -m pip install --upgrade pip setuptools pyopenssl
    python -m pip install --upgrade httpie
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: tests
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test
    - stage: test
      jdk: openjdk11
      name: tests (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test
    - stage: test
      jdk: openjdk8
      name: default tasks
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk11
      name: default tasks (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk8
      name: gradle dependencyUpdates
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates
    - stage: test
      jdk: openjdk11
      name: gradle dependencyUpdates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates
#    - stage: deploy
#      #jdk: openjdk8
#      jdk: openjdk11
#      name: GitHub release and GitHub pages deployment (openjdk11)
#      script: skip
#      if: branch = "master" AND type NOT IN (pull_request)
#      before_deploy:
#        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
#        - env
#        # documentation
#        - cd $TRAVIS_BUILD_DIR && ./gradlew npm_run_gh-pages
#      deploy: &pages
#        provider: pages
#        skip-cleanup: true
#        github-token: "$GITHUB_TOKEN"
#        keep-history: true
#        local-dir: .vuepress/dist
#        target_branch: gh-pages
#        on:
#          branch: master
#          condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  directories:
    - ~/.gradle
  packages: true
  pip: true
